title: Degustująca Istota # your site title
author: Danuta Irena Żabińska
email: degustujaca.istota@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Testerski blog o restauracjach. Recenzje degustowanych dań. Ranking najlepszych restauracji w Polsce.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.degustujacaistota.pl/" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: Degustująca-Istota-309847352979817 # replace with your_facebook_username or comment to remove link from footer
github_username:  DanutaZabinska # replace with your_github_username or comment to remove link from footer
instagram_username: degustujacaistota # replace with your_instagram_username or comment to remove link from footer
social:
  name: Danuta Żabińska
  links:
    - https://www.instagram.com/degustujacaistota/
    - https://www.facebook.com/Degustująca-Istota-309847352979817/
    - https://www.linkedin.com/in/danuta-żabińska-94a74410b/
#    - https://plus.google.com/+BenBalter
    - https://github.com/DanutaZabinska
#    - https://keybase.io/benbalter

# disqus:
#  shortname: Danusia # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
